server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
# uri: scheme://service-name
# lb://order-service -- lb: Load Balancer.
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
        - id: product-service
          uri: http://localhost:3000
          predicates:
            - Path=/api/product/**
        - id: discovery-service
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/website
          filters:
            - SetPath=/
        - id: discovery-service-fe
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
logging:
  level:
    root: WARN
    org:
      springframework:
        cloud:
          gateway: INFO
