server:
  port: 0
spring:
  application:
    name: inventory-service
  data:
    jdbc:
      dialect: mysql
  datasource:
    url: jdbc:mysql://localhost:3309/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
