## Use a lightweight Java runtime
#FROM openjdk:21-jdk-slim
#
## Argument to specify the path to the JAR file
#ARG JAR_FILE=target/*.jar
#
## Copy the built JAR file into the image
#COPY ${JAR_FILE} app.jar
#
## Open port 3000 (not required for function, but for documentation and runtime mapping)
#EXPOSE 3000
#
## Run the Spring Boot app
#ENTRYPOINT ["java", "-jar", "/app.jar"]
