services:
  mysql-inventory:
    image: mysql
    restart: always
    container_name: mysql-inventory
    env_file:
      - .env
    ports:
      - "3309:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - app_net
    volumes:
      - ./data:/data/db
networks:
  app_net: